# Entry.create!(name: "Matz")
# Entry.create!(name: "Yehuda Katz")
# Entry.create!(name: "DHH")
# Entry.create!(name: "Jose Valim")
# Entry.create!(name: "Dr Nic")
# Entry.create!(name: "John Nunemaker")
# Entry.create!(name: "Aaron Patterson")

Book.create!(title: "B-25")
Book.create!(title: "Lili4ka")
Book.create!(title: "No!")